# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: MSFT Lab

stages:
- stage: 'DefinePublisher'
  displayName: "Define Publisher Resources"
  jobs:
  - job: "DefinePublisherResourcesJob"
    displayName: "Define Publisher Resource Job"
    steps:
      - script: |
           echo creating publisher resources
           cd /home/azureuser/stratumaosm/stratum/aosm
           ./publisher_step1.sh
- stage: 'DefineAppVersion'
  jobs:
  - job: "DefineAppVersionJob"
    displayName: "Create App Version Job"
    steps:
      - script: |
           echo defining app version
           cd /home/azureuser/stratumaosm/stratum/aosm
           ./uploadArtefacts.sh
           ./publisher_step2.sh
- stage: 'DeployApp'
  jobs:
  - job: "DeployAppJob"
    displayName: "DeployAppJob"
    steps:
      - script: |
           cd /home/azureuser/stratumaosm/stratum/aosm
           ./deploy_operator.sh

