{{- if not .Values.global.ssh_Secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.ssh_SecretsName }}
type: Opaque
data:
  id_rsa: {{ .Values.global.id_rsa_key }}
  id_rsa.pub: {{ .Values.global.id_rsa_pub_key }}
  id_dsa: {{ .Values.global.id_dsa_key }}
  id_dsa.pub: {{ .Values.global.id_dsa_pub_key }}
{{- end }}
