apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.headlessService.name }} 
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app:  {{ .Values.global.headlessService.selectorAppName }}
  ports:
  - port: 80   # port stanza required but not used by k8s for headless service
    name: web
